version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - alias-mac
  assignees:
  - alias-mac
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.1
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.0
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.15
    - 7.13.8
  - dependency-name: concurrently
    versions:
    - 6.0.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.20.0
    - 4.21.0
  - dependency-name: commitlint
    versions:
    - 12.0.1
    - 12.1.0
    - 12.1.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
    - 12.1.0
    - 12.1.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
    - 12.1.0
    - 12.1.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@types/mongodb"
    versions:
    - 3.6.1
    - 3.6.10
    - 3.6.9
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
    - 7.12.17
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: standard-version
    versions:
    - 9.1.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
